### ISSUE TITLE
Parameter debug is set to true for insertAll by Standard

### ISSUE THREAD

**Issue by harald-schafer** [biner88/mysql_utils#10]
Hi I wonder if the parameter debug is supposed to be set to true by standard for function insertAll?

`  Future<int> insertAll({
    required String table,
    required List<Map<String, dynamic>> insertData,
    replace = false,
    debug = true,
  }) async {
`

**Comment by biner88** [comment]
This is an error and should be false by default. ~~Immediately release a new version to fix it.~~
Please update to 2.1.0
