### ISSUE TITLE
Charset Support for Emoji

### ISSUE THREAD

**Issue by seceba** [biner88/mysql_utils#12]
Greetings,

I get an error when I try to save an emoji to my database or read a saved emoji.

Error:

**MySQLServerException [1366]: Incorrect string value: '\xF0\x9F\x98\x87' for column `too`.`poo`.`foo` at row 1**

This is because mysql_client uses utf8 by default.

If you use the following option in the connection.dart file in the mysql_client package 
   
```
 await execute(
      'SET @@collation_connection=$_collation, @@character_set_client=utf8, @@character_set_connection=utf8, @@character_set_results=utf8',
    );
```

If you change from the above code to the following code, that is, if you change the charsets from utf8 to utf8mb4, the problem will be fixed.

```
  await execute(
      'SET @@collation_connection=$_collation, @@character_set_client=utf8mb4, @@character_set_connection=utf8mb4, @@character_set_results=utf8mb4',
    ); 
```

This problem is on the mysql_client side but I think you can fix it by taking a small parameter.

Have a good day.

**Comment by biner88** [comment]
```
 var db = MysqlUtils(
  settings: {
    'host': '127.0.0.1',
    'port': 3306,
    'user': 'root',
    'password': 'root',
    'db': 'test',
    'maxConnections': 10,
    'secure': false,
    'prefix': 'prefix_',
    'pool': true,
    'collation': 'utf8mb4_general_ci',
  },
```
I think the collation can be set to utf8mb4 during initialization.

**Comment by seceba** [comment]
Hi, collations and charsets are different things. by setting collation you are telling what the structure can hold, but when we write the data we have to tell which charset to write with.

**Comment by biner88** [comment]
I see, you also mentioned the same problem in mysql_client. If mysql_client is updated, it will also be updated here.
