### ISSUE TITLE
Can't connect with no password

### ISSUE THREAD

**Issue by azliR** [biner88/mysql_utils#18]
When connecting with password `null` or `''` it return this:
```
MySQLServerException [1045]: Access denied for user 'root'@'localhost' (using password: YES)
```
But when i create new user with password, it's fine.

**Comment by enwi** [comment]
Getting the same error when using mariadb and an empty password

**Comment by biner88** [comment]
Yes, it has not been updated for a long time due to the ongoing war in the country where the author of mysql_client lives.
