### ISSUE TITLE
Feature request - order by

### ISSUE THREAD

**Issue by piotrszpruta** [biner88/mysql_utils#2]
Hey, idk if its fine to ask for features there, but could you please add order by function?

**Comment by biner88** [comment]
Hi, it supports `order`,`group`, and `having`.  
`getAll `, `getOne` can use.
Use like below:

```
var row = await db.getAll(
  table: 'table',
  fields: '*',
  order:'id desc',
  where: {'email': 'xxx@google.com','id': ['between', '1,4'],'email': ['=', 'sss@google.com'],'news_title': ['like', '%name%'],'user_id': ['>', 1]},
);
print(row);
```

**Comment by piotrszpruta** [comment]
Oh okay thanks, I think I didn't saw anything about that in docs
