### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by igotfr** [biner88/mysql_utils#3]
### table Product:
| id | description | quantity | price |
| -- | --------------- | ---------- | ------- |
| 1 | Bean | 3 | 4.7
| 2 | Rice | 5 | 15
| 3 | Flour | 15 | 2.5

### Query
```dart
await conn.getAll(table: 'Product', fields: '*', where: {'id': ['>', 1]});
```

### Exepected
| id | description | quantity | price
| -- | --------------- | ---------- | ------- |
| 2 | Rice | 5 | 15
| 3 | Flour | 15 | 2.5

### Getted
| id | description | quantity | price
| -- | --------------- | ---------- | ------- |
| 1 | Bean | 3 | 4.7

**Comment by biner88** [comment]
Yes, I'll verify it further!

**Comment by biner88** [comment]
Hi,@cindRoberta This bug has been fixed, thanks for your feedback.

**Comment by igotfr** [comment]
@biner88 other query not running

### table Product:
| id | description | quantity | price |
| -- | --------------- | ---------- | ------- |
| 1 | Bean | 3 | 4.7
| 2 | Rice | 5 | 15
| 3 | Flour | 15 | 2.5
| 4 | Axe | 3 | 18.6
| 5 | Broom | 8 | 7.3

### Query
```dart
await conn.getAll(table: 'Product', fields: '*', where: {'id': ['between', '2,4']});
```

### Exepected
| id | description | quantity | price
| -- | --------------- | ---------- | ------- |
| 2 | Rice | 5 | 15
| 3 | Flour | 15 | 2.5
| 4 | Axe | 3 | 18.6

### Getted
Internal Server Error
RangeError (index): Invalid value: Not in inclusive range 0..1: 2

**Comment by biner88** [comment]
This is a document error, the correct one should be

```
await conn.getAll(table: 'Product', fields: '*', where: {'id': ['between', 2,4]});
``` 
@cindRoberta
