### ISSUE TITLE
Unhandled Exception: Bad state: Cannot write to socket, it is closed

### ISSUE THREAD

**Issue by mayur-16** [biner88/mysql_utils#5]
am using your package for standalone desktop application with mysql local database.
this works fine when mysql workbench is open but when pc is restarted i'll loose mysql instance and get the error listed above.
Is there any method to programmatically start Mysql connection?

**Comment by mayur-16** [comment]
i dont know how to use 
`var connection=await db1.createConnection();`

i am getting error when tried to use it in initstate.

**Comment by biner88** [comment]
I'm so sorry, your answer may be found [here](https://github.com/adamlofts/mysql1_dart/issues?q=Cannot+write+to+socket).

**Comment by mayur-16** [comment]
Can you please give the sample code for reestablishing connnection between mysql database and flutter when isconnectionAlive()=false? It would be really helpful..

**Comment by biner88** [comment]
```
 void testConnect() async {
    var res = await db.isConnectionAlive();
    print(res);
  }

  Timer.periodic(const Duration(seconds: 3), (timer) {
    testConnect();
  });
```
```
Future<bool> isConnectionAlive() async {
    try {
      await (await conn).query('select 1', []).timeout(
          Duration(milliseconds: 500), onTimeout: () {
        throw TimeoutException('test isConnectionAlive timeout.');
      });
      return true;
    } catch (e) {
      conn = createConnection();
      return false;
    }
  }
```
isConnectionAlive() will automatically start mysql again.
I don't know if it will help.
@mayur-16

**Comment by mayur-16** [comment]
package works perfectly fine only when if the MySql workbench is opened before this flutter app.
i dont know whether i have to configure any settings in Mysql in my machine to allow access to fetch data directly..

problem is **whenenever have to use my application ,first i have to open Mysql through command line client. i dont want this extra task . is there any workaround?**


here is my simple code..

```
import 'dart:developer';
import 'package:flutter/material.dart';
import 'package:mysql_utils/mysql1/src/single_connection.dart';
import 'package:mysql_utils/mysql_utils.dart';


class Homepage extends StatefulWidget {
  const Homepage({Key? key}) : super(key: key);

  @override
  _HomepageState createState() => _HomepageState();
}


class _HomepageState extends State<Homepage> {
  MysqlUtils? db;

  @override
  void initState() {
    super.initState();
    initializeDatabase();
  }
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      
      body: Center(
            child: TextButton.icon(
                onPressed: () {
                  log("pressed");
                  db!=null? getDatafromdatabase():ScaffoldMessenger.of(context)
                      .showSnackBar(const SnackBar(content: Text("Please wait a second..")));
                },
                icon: const Icon(Icons.get_app),
                label: const Text("get data!")),
          ),
    );
  }

  void getDatafromdatabase() async {
  
    log("getting data",name: "data");
	
	Results row = await db!.query('SELECT * FROM mydetails',[]);
    log(row.toString(), name: "results");
	
  }
  
  void initializeDatabase(){
    MysqlUtils(
        settings: ConnectionSettings(
          //host: '192.168.**.***',
          host: 'localhost',
          port: 3306,
          user: 'root',
          password: '*****',
          db: 'login',
          useCompression: false,
          useSSL: false,
          timeout: const Duration(seconds: 8),
        ),
        pool: true,
        errorLog: (error) {
          log("-----$error",name: "error");
        },
        sqlLog: (sql) {
          log("-----$sql",name:"sql");
        },
        connectInit: (MysqlUtils db1) async{
          log("complete",name:"connectInit");
          db=db1;
        });
  }

}
```


and here is the console output..

```
Syncing files to device Windows...
Restarted application in 735ms.
[connectInit] complete
[log] pressed
[data] getting data
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Error 1156 (08S01): Got packets out of order
#0      Handler.checkResponse (package:mysql_utils/mysql1/src/handlers/handler.dart:77:7)
#1      QueryStreamHandler.processResponse (package:mysql_utils/mysql1/src/query/query_stream_handler.dart:50:18)
#2      ReqRespConnection._handleData (package:mysql_utils/mysql1/src/single_connection.dart:350:32)
#3      ReqRespConnection._handleHeader (package:mysql_utils/mysql1/src/single_connection.dart:319:13)
<asynchronous suspension>
#4      ReqRespConnection._readPacket (package:mysql_utils/mysql1/src/single_connection.dart:304:7)
<asynchronous suspension>
```

some times i get this error ,other times i get `bad state: cannot write to socket,it is closed` error.

i dont know whether its the issue from package or local Mysql server side.

am new to local database concepts(MySql). it would be very helpful if you helped me to sort out this issue .. thank you so much.

**Comment by biner88** [comment]
```
class Common {
   MysqlUtils get mysqlAPP => MysqlUtils(
        settings: ConnectionSettings(
          //host: '192.168.**.***',
          host: 'localhost',
          port: 3306,
          user: 'root',
          password: '*****',
          db: 'login',
          useCompression: false,
          useSSL: false,
          timeout: const Duration(seconds: 8),
        ),
        pool: true,
        errorLog: (error) {
          log("-----$error",name: "error");
        },
        sqlLog: (sql) {
          log("-----$sql",name:"sql");
        },
        connectInit: (MysqlUtils db1) async{
          log("complete",name:"connectInit");
          db=db1;
        });
}
```
```
Results row = await Common.mysqlAPP!.query('SELECT * FROM mydetails',[]);
```

The code is not tested. The principle is that all classes that use this method inherit this class and initialize it every time they are used. This package is more suitable for the server side. I don't understand English very well, so I used Google Translate.

**Comment by harald-schafer** [comment]
@biner88 
I had a similar issue with the "re"connection (let's better say after timeout I always needed to check if connection is alive).
I actually solved it by patching your code in two locations in this way
///query
  Future<Results> query(String sql, List<Object?>? values,
      {debug = false}) async {
    var queryStr = '$sql  $values';
    queryTimes++;
    if (debug) _sqlLog(queryStr);
// BEGIN INSERT CODE
    await isConnectionAlive();
// END INSERT CODE
    var res = await (await conn).query(sql, values);
    return res;
  }

I did the same in queryMulti and for me know it always works because as you mentioned above the isConnectionAlive successfully reconnects in case the mysql connection has times out.

**Comment by mayur-16** [comment]
i cleared the issue using [this step](https://stackoverflow.com/a/56752560/14098933)..
now app is working perfectly fine even without opening work bench to create local mysql instance.
