### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'String'

### ISSUE THREAD

**Issue by mayur-16** [biner88/mysql_utils#7]
am trying to update the table using db.update() function

here is my code

 ```
MysqlUtils db = MysqlUtils(
        settings: {
          'host': 'localhost',
          'port': 3306,
          'user': 'root',
          'password': '***',
          'db': '***',
          'maxConnections': 10,
          'secure': false,
          'pool': true,
          'collation': 'utf8mb4_general_ci',
        },
        errorLog: (error) {
          print(error);
        },
        sqlLog: (sql) {
          print(sql);
        },
        connectInit: (db1) async {
          print('whenComplete');
        }
    );
```

`int results=await db.update(table: 'userdetails', updateData: {'username': 'myname'}, where: {'userid': 2});`

**Comment by biner88** [comment]
mysql_utils version?

**Comment by mayur-16** [comment]
> mysql_utils version?

version 2.0.10 

i tried to update table using 

`var results=await db.query('UPDATE userdetails SET username="xxx" WHERE userid=2');`
it worked..


 ` int results=await db.update(table: 'userdetails', updateData: {'username': 'xxx'}, where: {'userid': 2});`
but this didnt work..

**Comment by biner88** [comment]
I test is OK
```
  int results = await db.update(
      table: 'userdetails',
      updateData: {'username': 'xxx'},
      where: {'userid': 2});
  print(results);
```
Please copy the create sql statement of userdetails table.

**Comment by mayur-16** [comment]
> I test is OK
> 
> ```
>   int results = await db.update(
>       table: 'userdetails',
>       updateData: {'username': 'xxx'},
>       where: {'userid': 2});
>   print(results);
> ```
> 
> Please copy the create sql statement of userdetails table.

issue solved!!

turned out i missed prefix field in settings..
thank you so much for your quick response.

**Comment by mayur-16** [comment]
thank you
