### ISSUE TITLE
How can i connect app in multiple pc in network with one pc having database? 

### ISSUE THREAD

**Issue by mayur-16** [biner88/mysql_utils#8]
Am trying to connect multiple computers in network to one  mysql server.
I want the windows applications which uses this package to access single server through local network.

**i tried using ip address instead of local host in host property**, 

but network computers couldn't access data.

Is there any way i could make it work..? 

**Thanks in advance**.

**Comment by xsonicaudio** [comment]
Mysql opens port 3306 for remote access

**Comment by biner88** [comment]
Mysql opens port 3306 for remote access.

**Comment by mayur-16** [comment]
I had to make some configurations in mysql workbench.. now its working fine, thank you!
